name: journal-app
namespace: default

replicas: 1

appDebug: "0"
appHostName: simplememo.org
dbHost: journal-app-data-headless
dbPort: 5432


volumes:
  - name: static-files
    emptyDir: {}

image:
  repository: ""
  tag: ""
  pullPolicy: Always

initContainers:
  - name: journal-app-migrate

port: 8000

envFrom:
  - configMapRef:
      name: app-config
  - secretRef:
      name: app-secrets

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  - name: Host
    value: simplememo.org
    path: /ready/
    initialDelaySeconds: 15
    periodSeconds: 5

livenessProbe:
  - name: Host
    value: simplememo.org
    path: /health/
    initialDelaySeconds: 15
    periodSeconds: 20

hpa:
  name: journal-app-hpa
  minReplicas: 1
  maxReplicas: 5
  metrics:
    type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50