apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
        {{ range .Values.volumes }}
        - name: {{ .name}}
            {{- if .emptyDir }}
          emptyDir: { toYaml .emptyDir | nindent 12 }
            {{ end }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{ end }}
        {{ end }}
      initContainers:
        {{ range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .imagePullPolicy }}
          command: [ "sh", "-c", "cp -r /app/staticfiles/* /static-files/" ]
          volumeMounts:
            {{ range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{ end }}
         {{ end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
              {{ range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
                {{ end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
