apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-app
  template:
    metadata:
      labels:
        app: journal-app
    spec:
      volumes:
        - name: static-files
          emptyDir: {}

      initContainers:
        - name: migrate
          image: eoinkyne/journal-app:0.0.3
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

      containers:
        - name: journal-app
          image: eoinkyne/journal-app:0.0.3
          imagePullPolicy: IfNotPresent
          command: ["gunicorn"]
          args:
            ["journal.wsgi:application", "--bind", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles/
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: simplememo.org
              path: /ready/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: simplememo.org
              path: /health/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20