apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: journal-app-data
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-app-data
  template:
    metadata:
      labels:
        app: journal-app-data
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: journal-app-data
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: journal-app-data-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: journal-app-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard