name: journal-app-data
namespace: default

replicas: 1
host: simplememo.org
port: 5432

serviceName: journal-app-data-headless
debug: "0"

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: "5432"
  clusterIP: None

securityContext:
  fsGroup: 999

envFrom:
  - secretRef:
      name: app-secrets

volumneMounts:
  - name: journal-app-data-storage
    mountPath: /var/lib/postgresql/data

persistence:
  name: journal-app-data-storage
  enabled: true
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5