name: Build and publish Docker image
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  #    - main
  #pull_request:
  #  branches:
  #    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Extract version
        id: vars
        run: echo "VERSION=0.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Build and push journal-app image (multi-arch + cache)
        uses: docker/build-push-action@v5
        with:
          context: ./journal_app/
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_REPO }}/journal-app:${{ steps.vars.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_REPO }}/journal-app:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push journal-app-web image (multi-arch + cache)
        uses: docker/build-push-action@v5
        with:
          context: ./nginx/
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_REPO }}/journal-app-web:${{ steps.vars.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_REPO }}/journal-app-web:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: publish
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Create Kubernetes secrets
        run: |
          kubectl create secret generic app-secrets \
            --from-literal=SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --from-literal=POSTGRES_DB="{{ secrets.DB }}" \
            --from-literal=POSTGRES_USER="{{ secrets.POSTGRES_USER }}" \
            --from-literal=POSTGRES_PASSWORD="{{ secrets.POSTGRES_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -
      - name: Deploye with Helm
        run: |
          /usr/local/bin/helm upgrade --install journal-app ./helm/journal-app \
          --values helm/journal-app/values.yaml \
          --set image.repository="${{ secrets.DOCKER_HUB_REPO }}/journal-app",image.tag="${{ steps.vars.outputs.VERSION }}"
          /usr/local/bin/helm upgrade --install journal-app-web helm/journal-app-web \
          --values helm/journal-app-web/values.yaml \
          --set image.repository="${{ secrets.DOCKER_HUB_REPO }}/journal-app-web",image.tag="${{ steps.vars.outputs.VERSION }}"
      - name: Verify rollout status
        run: |
          kubectl rollout status deployment/journal-app
          kubectl rollout status deployment/journal-app-web