name: Build and publish Docker image
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
  #    - main
  #pull_request:
  #  branches:
  #    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Extract version
        id: vars
        run: echo "VERSION=0.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Build and push journal-app image (multi-arch + cache)
        uses: docker/build-push-action@v5
        with:
          context: ./journal_app/
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/journal-app:${{ steps.vars.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USER }}/journal-app:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push journal-app-web image (multi-arch + cache)
        uses: docker/build-push-action@v5
        with:
          context: ./nginx/
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/journal-app-web:${{ steps.vars.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USER }}/journal-app-web:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: publish
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Update image tags
        run: |
          sed -i "s|image: .*/journal-app:.*|image: "eoinkyne/journal-app:0.0.32"|g" k8s/journal_app.yaml
          sed -i "s|image: .*/journal-app:.*|image: "eoinkyne/journal-app-web:0.0.32"|g" k8s/journal_app_web.yaml
          sed -i "s|image: .*/journal-app-web:.*|image: "eoinkyne/journal-app-web:0.0.32"|g" k8s/journal_app_web.yaml
      - name: Show rendered YAML files
        run: |
          nl -ba k8s/journal_app.yaml
          nl -ba k8s/journal_app_web.yaml
      - name: Deploy to minikube
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/journal_app
          kubectl rollout status deployment/journal_app_web