name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - feature-create-githubactions-workflow-for-tests

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testuserpassword
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d journal_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_DB: test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuserpassword
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./journal_app/requirements.txt

      - name: Run tests
        working-directory: ./journal_app
        run: |
          python manage.py test